title: GTP Concerns & Issues
description: A public resource documenting concerns, issues and general transparency around quirks with the LMDh cars on iRacing. 
theme: just-the-docs

url: https://samwinton.github.io
color_scheme: dark
